[package]
name = "wyrdwest_service"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
log = "0.4.6"
log4rs = "0.8.3"
config = "0.9.2"
actix-web = "1.0.0-alpha.6"
